version: "3.7"

services:
  next-admin-server:
    container_name: next-admin-server
    image: nginx:latest
    volumes:
      - ./deploy/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: unless-stopped

  next-admin:
    container_name: next-admin
    build:
      context: .
      dockerfile: ./deploy/app/Dockerfile
    volumes:
      - .:/app
